[settings]
idiomatic_version_file_enable_tools = ["ruby"]
env_shell_expand = true
experimental = true

[settings.ruby]
compile = false

[tools]
age = "latest"
"aqua:go-task/task" = "latest"
buf = "latest"
dart = { version = "3", url = "https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-macos-arm64-release.zip", version_expr = 'fromJSON(body).prefixes | filter({ # matches "^channels/stable/release/(\\d+\\.\\d+\\.\\d+)/$" }) | map({split(#, "/")[3]}) | sortVersions()', version_list_url = "https://storage.googleapis.com/storage/v1/b/dart-archive/o?prefix=channels/stable/release/&delimiter=/" }
direnv = "latest"
"gem:cocoapods" = "latest"
gh = "latest"
go = "1"
helm = "latest"
java = "25"
maestro = "latest"
node = "24"
pnpm = "latest"
ruby = "4.0"
sops = "latest"
swiftgen = { version = "latest", exe = "swiftgen/bin/swiftgen" }
uv = "latest"
xcbeautify = "latest"
xcodes = "latest"
yq = "latest"
