[settings]
idiomatic_version_file_enable_tools = ["ruby"]
env_shell_expand = true

[settings.ruby]
compile = false

[tools]
age = "latest"
"aqua:go-task/task" = "latest"
buf = "latest"
cmake = "latest"
direnv = "latest"
"gem:cocoapods" = "latest"
gh = "latest"
go = "1"
helm = "latest"
java = "26.0.0"
maestro = "latest"
node = "24"
pnpm = "latest"
ruby = "4.0"
sops = "latest"
swiftgen = { version = "latest", exe = "swiftgen/bin/swiftgen" }
uv = "latest"
xcbeautify = "latest"
xcodes = "latest"
yq = "latest"
